F90FLAGS += -I../../src
LDFLAGS = -ldftatom -L../../src

export LDFLAGS

all:
	cd lda; make -f Makefile.manual
	cd lda; make -f Makefile_6.manual
	cd rlda; make -f Makefile.manual
	cd atom_U; make -f Makefile.manual

test:
	cd lda; make -f Makefile.manual test
	cd lda; make -f Makefile_6.manual test
	cd rlda; make -f Makefile.manual test
	cd atom_U; make -f Makefile.manual test

clean:
	cd lda; make -f Makefile.manual clean
	cd lda; make -f Makefile_6.manual clean
	cd rlda; make -f Makefile.manual clean
	cd atom_U; make -f Makefile.manual clean
